#!/usr/bin/env python3
"""Full-Foundation pairing sweep.

For every header under the project that declares Objective-C methods
(an @interface or @protocol block), every selector declared there must be
implemented somewhere in the .m sources. Exits non-zero (FAIL) when any
declared selector has no implementation.

Usage:  pairing_sweep.py [ROOT]
        ROOT defaults to the directory containing this script.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__)) if len(sys.argv) < 2 else sys.argv[1]

# Selectors the mechanical parser cannot see as implemented, verified by hand
# to exist in the sources. Each entry: (header basename, selector, where implemented).
ALLOWLIST = [
    # All 15 -initWith* are macro-generated by __NSNUMBER_INIT at
    # Numeric.subproj/NSNumber.m:108-122 (the macro body spells
    # "- (instancetype)initWith##name:(type)value"), so the plain
    # implementation scanner never finds their text.
    ('NSNumber.h', 'initWithBool', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithChar', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithDouble', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithFloat', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithInt', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithInteger', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithLong', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithLongLong', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithShort', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithUnsignedChar', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithUnsignedInt', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithUnsignedInteger', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithUnsignedLong', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithUnsignedLongLong', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    ('NSNumber.h', 'initWithUnsignedShort', 'Numeric.subproj/NSNumber.m:108-122 (__NSNUMBER_INIT)'),
    # Multiline NS_SWIFT_UNAVAILABLE(...) attributes between the return type and
    # the selector split the declaration across lines that trip the flat scanner.
    ('NSCoder.h', 'decodeTopLevelObjectForKeyerrorofforKey', 'Serialization.subproj/NSCoder.m:633'),
    ('NSCoder.h', 'decodeTopLevelObjectOfClassforKeyerrorofforKey', 'Serialization.subproj/NSCoder.m:637'),
    ('NSCoder.h', 'decodeTopLevelObjectOfClassesforKeyerrorofforKey', 'Serialization.subproj/NSCoder.m:643'),
    # Variadic "...," after the last parameter makes the selector not the last
    # token before ';', confusing the declaration matcher.
    ('NSString.h', 'initWithFormat', 'String.subproj/NSString.m:95'),
]


def selectors_header(src):
    out = set()
    chunks = re.split(r'^@(?:interface|implementation|protocol)\b', src, flags=re.M)
    for c in chunks:
        flat = re.sub(r'-\s*\([^)]*\)(?:[^;\n{}]|\n)+?;?', lambda mo: mo.group(0).replace('\n', ' '), c)
        for k in ('-', '+'):
            for decl in re.findall(re.escape(k) + r'\s*\([^)]*\)\s*([^;{]+?)\s*;', flat):
                parts = re.findall(r'([a-zA-Z_][a-zA-Z0-9_]*):', decl)
                if parts:
                    out.add(''.join(parts))
                else:
                    name = decl.strip().split(' ')[0]
                    if re.match(r'[a-zA-Z_][a-zA-Z0-9_]*$', name):
                        out.add(name)
    return out


def selectors_impls(src):
    out = set()
    flat = src.replace('\n', ' ')
    for k in ('-', '+'):
        for decl in re.findall(re.escape(k) + r'\s*\([^)]*\)\s*([^;{]+?)\s*[{;]', flat):
            parts = re.findall(r'([a-zA-Z_][a-zA-Z0-9_]*):', decl)
            if parts:
                out.add(''.join(parts))
            else:
                name = decl.strip().split(' ')[0]
                if re.match(r'[a-zA-Z_][a-zA-Z0-9_]*$', name):
                    out.add(name)
    return out


def main():
    subdirs = sorted(d for d in os.listdir(ROOT)
                     if os.path.isdir(os.path.join(ROOT, d)))
    m_texts = []
    for d in subdirs:
        dd = os.path.join(ROOT, d)
        for f in sorted(os.listdir(dd)):
            if f.endswith('.m'):
                m_texts.append(open(os.path.join(dd, f)).read())
    impl = selectors_impls(' '.join(m_texts))

    failures = 0
    total_decl = 0
    allowlisted = 0
    print('%-30s %5s %6s   missing' % ('header', 'decl', 'missing'))
    for subdir in subdirs:
        dd = os.path.join(ROOT, subdir)
        for f in sorted(os.listdir(dd)):
            if not f.endswith('.h'):
                continue
            hf = os.path.join(dd, f)
            src = open(hf).read()
            if '@interface' not in src and '@protocol' not in src:
                continue
            hs = selectors_header(src)
            if not hs:
                continue
            total_decl += len(hs)
            blocked = {entry[1] for entry in ALLOWLIST if entry[0] == f}
            missing = sorted(s for s in hs if s not in impl)
            real = [s for s in missing if s not in blocked]
            hit = [s + ' [allowlisted]' for s in missing if s in blocked]
            allowlisted += len(hit)
            print('%-30s %5d %6d   %s' % (f, len(hs), len(missing), ' '.join(real + hit)))
            if real:
                failures += 1
    print('PAIRING SWEEP: headers=%d declared=%d allowlisted=%d failing-headers=%d FAIL=%d'
          % (count_headers(ROOT, subdirs), total_decl, allowlisted, failures, int(failures > 0)))
    return 1 if failures else 0


def count_headers(root, subdirs):
    n = 0
    for d in subdirs:
        dd = os.path.join(root, d)
        for f in sorted(os.listdir(dd)):
            if f.endswith('.h'):
                src = open(os.path.join(dd, f)).read()
                if ('@interface' in src or '@protocol' in src) and selectors_header(src):
                    n += 1
    return n


if __name__ == '__main__':
    sys.exit(main())